### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by BenAuxier** [baoxingsong/GEAN#5]
Build failed after 100% on Ubuntu 18.04.3 using GCC version 7.4.0

Error code is as follows:

[ 98%] Building CXX object CMakeFiles/gean.dir/src/impl/outPutORFConserveredTranscripts.cpp.o
In file included from /home/auxie001/GEAN/src/impl/../model/model.h:41:0,
                 from /home/auxie001/GEAN/src/impl/outPutORFConserveredTranscripts.h:8,
                 from /home/auxie001/GEAN/src/impl/outPutORFConserveredTranscripts.cpp:5:
/home/auxie001/GEAN/src/impl/../model/OrthologPair.h:53:1: warning: multi-line comment [-Wcomment]
 //    uint32_t getQueryMiddlePos() const;\
 ^
/home/auxie001/GEAN/src/impl/outPutORFConserveredTranscripts.cpp: In function ‘void outPutORFConserveredTranscripts(const string&, const string&, const string&, const int&, std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&)’:
/home/auxie001/GEAN/src/impl/outPutORFConserveredTranscripts.cpp:27:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                      for (int index = 0; index < gene.getTranscripts().size(); ++index) {
                                          ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[100%] Linking CXX executable gean
CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.o: In function `checkElements(int const&, int const&, std::vector<SpliceSitePosition, std::allocator<SpliceSitePosition> > const&, int const&)':
/home/auxie001/GEAN/src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp:35: multiple definition of `checkElements(int const&, int const&, std::vector<SpliceSitePosition, std::allocator<SpliceSitePosition> > const&, int const&)'
CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanForTranscript.cpp.o:/home/auxie001/GEAN/src/myImportandFunction/alignNeedlemanForTranscript.cpp:394: first defined here
collect2: error: ld returned 1 exit status
CMakeFiles/gean.dir/build.make:2229: recipe for target 'gean' failed
make[2]: *** [gean] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/gean.dir/all' failed
make[1]: *** [CMakeFiles/gean.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by baoxingsong** [comment]
I am sorry, I pushed a test version. This problem should be fixed at the latest push. You could pull it or clone it again.
