### ISSUE TITLE
gff2seq   minimum intron size for ORF stats checking error

### ISSUE THREAD

**Issue by elor77** [baoxingsong/GEAN#6]
Hi Baoxing 
In gean gff2seq:
when using argument:
`-m INT    minimum intron size for ORF stats checking`
I tried different values, always getting error: 
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)
```
Elad

**Comment by baoxingsong** [comment]
Thank you so much for the report. It could be fixed.
