### ISSUE TITLE
transgff

### ISSUE THREAD

**Issue by sabine004** [baoxingsong/GEAN#7]
Dear boiaxingsong,

I am trying to use the transgff function, but I cannot seem to find the right input for the -a similar segments option. I cannot get it to run without it. I tried using a sam output allignment between the two genomes between I am trying to transfer the genomen, but it is not working. I am trying to liftover the annotation from a previous version of the genome to a new version.

I hope you can help me.

Best wishes,
Sabine

**Comment by baoxingsong** [comment]
I guess you may would like to try this https://github.com/baoxingsong/GEAN/blob/master/example/transformMaizeGFFannotation.md

**Comment by sabine004** [comment]
Thank you for your quick reply. I will try to do that.

Best wishes,
Sabine
